kind: pipeline
name: build
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    when:
      branch:
        - never # should be master, but nevermind
    settings:
      dockerfile: docker/Dockerfile
      context: "."
      tag:
        - latest
      username:
        from_secret: global_docker_login
      password:
        from_secret: global_docker_password
      registry:
        from_secret: global_docker_registry
      repo:
        from_secret: docker_repo
