kind: pipeline
name: build
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    when:
      branch:
        - develop
    settings:
      dockerfile: docker/Dockerfile
      username:
        from_secret: docker_login
      password:
        from_secret: docker_password
      repo:
        from_secret: docker_repo
      registry:
        from_secret: docker_registry
