http:
  port: 3002
telegram:
  # Get it from bot father
  key: ''
  webhook:
    url: https://something.org:3002/webhook
    enabled: false
logger:
  level: info
vk:
  # Default path for POST requests from VK api
  endpoint: /
  groups: []
#  groups:
#    - id: 0
#      name: 'Group name'
#      testResponse: 'testResponseCode'
#      secretKey: 'groupSecretKey'
#      apiKey: 'callbackApiKey'
#      channels:
#        - id: '@pogonia_test_chan'
#          events:
#            - test
#            - another one
