http:
  port: 3002
telegram:
  key: ''
  webhookUrl: http://localhost:3002/webhook
logger:
  level: info
#vk:
#  groups:
#    - id: 0
#      name: 'Group name'
#      testResponse: 'testResponseCode'
#      secretKey: 'groupSecretKey'
#      apiKey: 'callbackApiKey'
#      channels:
#        - id: '@pogonia_test_chan'
#          events:
#            - test
#            - another one
