http:
  port: 3002
telegram:
  # Get it from bot father
  key: ''
  webhook:
    url: https://something.org:3002/webhook
    enabled: false
logger:
  level: info
vk:
  # Default path for POST requests from VK api
  endpoint: /
  groups: []
templates:
  message_new: templates/message_new.md
  wall_post_new: templates/post_new.md
#  groups:
#    - id: 0
#      name: 'Group name'
#      testResponse: 'testResponseCode'
#      secretKey: 'groupSecretKey'
#      apiKey: 'callbackApiKey'
#      channels:
#        - id: '@pogonia_test_chan'
#          events:
#            - wall_post_new
#            - post_suggestion
#            - group_join
#            - group_leave
#            - message_new

