http:
  port: 80
telegram:
  # Get it from bot father
  key: ''
  webhook:
    url: https://something.org/webhook
    enabled: false
postgres:
  uri: postgres://user:password@db/bot
logger:
  level: info
vk:
  # Default path for POST requests from VK api
  endpoint: /
  groups: []
templates:
  message_new: templates/message_new.md
  wall_post_new: templates/post_new.md
  group_join: templates/group_join.md
  group_leave: templates/group_leave.md
#  groups:
#    - id: 0
#      name: 'Group name'
#      testResponse: 'testResponseCode'
#      secretKey: 'groupSecretKey'
#      apiKey: 'callbackApiKey'
#      post_types: ['post','copy','reply','postpone','suggest']
#      channels:
#        - id: '@pogonia_test_chan'
#          events:
#            - wall_post_new
#            - post_suggestion
#            - group_join
#            - group_leave
#            - message_new

