name: Build & Publish

on:
  push:
    branches: [master]

jobs:
  push_to_registry:
    name: Build & Publish
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: git.vault48.org
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Extract docker metadata
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: git.vault48.org/${{ env.GITHUB_REPOSITORY }}
          
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}