# Docker-compose for dev purposes only
version: "3.7"
services:
  db:
    restart: always
    container_name: bot__db
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bot
    ports:
      - "5432:5432"
    volumes:
      - bot-db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
volumes:
  bot-db:
