version: '3.4'
services:
  db:
    container_name: bot-db
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bot
    volumes:
      - bot-db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
  app:
    restart: always
    environment:
      PORT: 80
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - ${EXPOSE}:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - node_modules:/app/node_modules
    entrypoint: node ./index.js
    depends_on:
      - db
volumes:
  bot-db:
  node_modules:
